### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by Okabintaro** [stinodego/python-cookiecutter#11]
I realize this might be a dumb question but could you please add a license? 
Don't really think a boilerplate like this is copyrightable but might be a good thing to do, just to be sure, [see this](https://choosealicense.com/no-permission/). Thanks!

Apart from that I quite like the setup with all the modern python tooling, so thanks for sharing and explaining it in the README!

**Comment by stinodego** [comment]
Thanks for the suggestion, I added a license! I'm glad you find this useful.

**Comment by Okabintaro** [comment]
Thanks, I am gonna include the license and mention this repo in my next project.
